/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const PlayLazyImport = createFileRoute('/play')()
const MatchLazyImport = createFileRoute('/match')()
const IndexLazyImport = createFileRoute('/')()
const LobbiesLobbyNameLazyImport = createFileRoute('/lobbies/$lobbyName')()

// Create/Update Routes

const PlayLazyRoute = PlayLazyImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/play.lazy').then((d) => d.Route))

const MatchLazyRoute = MatchLazyImport.update({
  id: '/match',
  path: '/match',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/match.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const LobbiesLobbyNameLazyRoute = LobbiesLobbyNameLazyImport.update({
  id: '/lobbies/$lobbyName',
  path: '/lobbies/$lobbyName',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/lobbies/$lobbyName.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/match': {
      id: '/match'
      path: '/match'
      fullPath: '/match'
      preLoaderRoute: typeof MatchLazyImport
      parentRoute: typeof rootRoute
    }
    '/play': {
      id: '/play'
      path: '/play'
      fullPath: '/play'
      preLoaderRoute: typeof PlayLazyImport
      parentRoute: typeof rootRoute
    }
    '/lobbies/$lobbyName': {
      id: '/lobbies/$lobbyName'
      path: '/lobbies/$lobbyName'
      fullPath: '/lobbies/$lobbyName'
      preLoaderRoute: typeof LobbiesLobbyNameLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/match': typeof MatchLazyRoute
  '/play': typeof PlayLazyRoute
  '/lobbies/$lobbyName': typeof LobbiesLobbyNameLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/match': typeof MatchLazyRoute
  '/play': typeof PlayLazyRoute
  '/lobbies/$lobbyName': typeof LobbiesLobbyNameLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/match': typeof MatchLazyRoute
  '/play': typeof PlayLazyRoute
  '/lobbies/$lobbyName': typeof LobbiesLobbyNameLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/match' | '/play' | '/lobbies/$lobbyName'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/match' | '/play' | '/lobbies/$lobbyName'
  id: '__root__' | '/' | '/match' | '/play' | '/lobbies/$lobbyName'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  MatchLazyRoute: typeof MatchLazyRoute
  PlayLazyRoute: typeof PlayLazyRoute
  LobbiesLobbyNameLazyRoute: typeof LobbiesLobbyNameLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  MatchLazyRoute: MatchLazyRoute,
  PlayLazyRoute: PlayLazyRoute,
  LobbiesLobbyNameLazyRoute: LobbiesLobbyNameLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/match",
        "/play",
        "/lobbies/$lobbyName"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/match": {
      "filePath": "match.lazy.tsx"
    },
    "/play": {
      "filePath": "play.lazy.tsx"
    },
    "/lobbies/$lobbyName": {
      "filePath": "lobbies/$lobbyName.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
